// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoWPr6pG372MwU-QzFvgW2YM43Aryqd_M',
    appId: '1:279297146388:web:f3a78a8a64d5f5ca50f101',
    messagingSenderId: '279297146388',
    projectId: 'newsapp-c80d3',
    authDomain: 'newsapp-c80d3.firebaseapp.com',
    storageBucket: 'newsapp-c80d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUAoxU2IuXyOFFuoUz6LuIK0_uv7DcO7Y',
    appId: '1:279297146388:android:23412d54835a7f0250f101',
    messagingSenderId: '279297146388',
    projectId: 'newsapp-c80d3',
    storageBucket: 'newsapp-c80d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEuXqXaZhkRL9EtLGw681lDFpW_83qUAA',
    appId: '1:279297146388:ios:fe6bddd128ed24ba50f101',
    messagingSenderId: '279297146388',
    projectId: 'newsapp-c80d3',
    storageBucket: 'newsapp-c80d3.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEuXqXaZhkRL9EtLGw681lDFpW_83qUAA',
    appId: '1:279297146388:ios:fe6bddd128ed24ba50f101',
    messagingSenderId: '279297146388',
    projectId: 'newsapp-c80d3',
    storageBucket: 'newsapp-c80d3.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoWPr6pG372MwU-QzFvgW2YM43Aryqd_M',
    appId: '1:279297146388:web:c6eb43f27ca19fe150f101',
    messagingSenderId: '279297146388',
    projectId: 'newsapp-c80d3',
    authDomain: 'newsapp-c80d3.firebaseapp.com',
    storageBucket: 'newsapp-c80d3.firebasestorage.app',
  );

}